baseURL = 'http://example.org/'
languageCode = 'en-us'
title = ''

theme = 'SimpleIntro'
[params]
    name = "Isaiah Cruz"
    mainTitle = " "
    mainText = "Actively seeking opportunities for employment and open to work."

[menus]
    [[menu.main]]
        identifier = "about"
        name = "Resume, Contact Info, and Important Links"
        url = "https://docs.google.com/document/export?format=docx&id=1VuvegJZgJn_F84fvN7oZTW0hSKncHsrJcuM9izDwsHc"