baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Isaiah Glenn Cruz'

theme = 'SimpleIntro'
[params]
    name = "Isaiah Cruz"
    mainTitle = " "
    mainText = "Actively seeking opportunities for employment and open to work."

[menus]
    [[menu.main]]
        identifier = "about"
        name = "ABOUT ME"
        url = "#about"
    [[menu.main]]
        identifier = "skills"
        name = "SKILLS"
        url = "#skills"
    [[menu.main]]
        identifier = "projects"
        name = "PROJECTS"
        url = "#projects"
